sudo: required

language: java

env:
  global:
  - secure: "tntEcXZM/gWbBmfqH+FWtNKANlxYRuIBsqtDQPgC9RJ4ezjyHj93/uJ2M70CQbz+I4aXC8S59eYkFMxjNm+UH3VNE11lqeHr5FCwFQU3WvPOXPFjsFqrWAmmiTfnapsQmnSiccm3/pNM6rSTpeoHWTxQxJ8AQEAg6y7Mz6R+1f/zF66xlqNmL2TRRD/gz9fu0FF4HRV/1igb0UhL11fZgsmvU8n6hlKr22mEyCH+QYLsw8s1Pyau29isZSyqP/QCcJTNFFFBmhhv97TZB8qYjvtiHzmZy2IEofOHb06EMnFFqOdHnSCh/xjrN/h9A79+BwHKIkdFto0hXwB0JcJfFqyccTuwsaseBBAM9pTscWT5EhLuIWKlRDMQwLoyygkjLFiEKYaIRgCEguhCIiQhVQMsd1NGXYIrj8n1CKNe5m3fwbRZPc32mc1FxUafZoIYJ2IqdjwZ5NX8lBBaizeJhZyzZ++iav6uChRJqPBYbuEwfM5+kGiNBbSElKZ7JZNRVirIykDEqUI9zwistL+bFRm3/ejbht/+jr1LjPHHA7P5uGYI/SwyiQma4E2FV87SZ17mTR3szbMQrFhZ4LNzgmyYveZ4rJrMI0uwr6KHmvU/I/B9cgq31zrXX52I/r4Cvm3L3ZVEDc3PGiakCKlwNqzV2JtHzsOAFyJDBkloMhQ="

addons:
  sonarcloud:
    organization: "gauravkgs1620"
    token:
      secure: $SONAR_TOKEN

jdk:
  - openjdk11
  
services:
  - docker

script: 
  - cd a4mee-api
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
