sudo: required

language: java

env:
  global:
  - DOCKER_USERNAME="FPbV2oUQ8NntKOKM6eTRQ2USPrNLi7OYapmaivyn+e+hs0847nzWDzSRxALuGojLKlenyc03yIa60KTYaK5HHJN1mrLCvXddZtGxeYpCVbv3ClsN+FJQgkYUo8Z48xlPvZwp6CNnINQEbXUpfQ1s4rby0UkBzpI035OEDkTlLLh3Sz6/07WA2I5i4xrDs5Q2m0GslkWomGgoIB9tuirfY1WQkWAGbkFfONRX0W9vjbT5+sKzGnEe5MlS7R1bcCjbiPvHerBB4d7EHmgjI77byjjPsalkb/bviDy66xNSGTM6uiCnRX0QhQPGFfXDSTABXF8sIkQMLyIZEx46qSn7RMkkreukZUtDxIjZOPH6jXizsI3Sq1fYzKMlVWlE+KpiYVQHu4jhVIe8u9p0efKZ68hBH27El5RU2u990FVU0TEOPTRZ+VbzXiIsZOZBV9amhwbaXvCb3QcEUQHhbR6RSBqHfrtzKo7nFGksmyOcTWQAzVozXd9WgWZGyZpOHcgOkyfeT+XCSbKIwxc65WDKqlQ6C43BJdOq9qtzeqoCrh2XM9fHS0LqPjwtLa24R2/N8Y1X3UQLG4XF8nUBq4WkBPwNCxb1L8+KjV03kgcEtWYe19KkJT1ier3eRNS2p2R4Jl5/FYy1LIVvvDrA2rpxSLhv3nnj/6vGGw7zONxNd7k="
  - DOCKER_PASSWORD="cvNaj5ZbctBNJpJzXmETVQH/nSuz6HRo5gc99/lG3Yho17hUpgCCcm+fyv0TSBDFZVbQjs74o1l1j9z5rhX0jK1AdGZdErypUkVwbXUpLzv2DXGxFEJELfJr/fpUUlfs4RZU1EC9AJMRilpILk3774/fdJhxJmiCb3QA5W89jAo0MkY6iULC060wPema67bpJiXRy6oTI4Nw/OmuipBOswC7vp7LTTC6pRvqM2exWRVFT1+LuQJpVrb8b7/FstX8xXu+sjM0C7Zryu34FWP6utWLSDEYHNRvAsJQ1jsmUH1dp7gmDeDTjCThqEj2K0BZISF9DYmWT6BOEMP2nc+7p7Aqh7MmBHmjPi4F4ubl4/RRI5v6Q763orErocvFNHrIo73YjuvZxFFOakHzR7NDRGqNIbZpntlwVS2P1p5DbVcc7+eeoRnKdBpeKv2+Q0/q5fnokMrC6BHK4BgvEF4yKZkhGL59Tl6nFA5t8nR1R9g04aoFTtceh1yWacNoAV3L5JfdBTYKLYoywHb5x4XkHlou38jnYMp4uFlQkzhrFNDCvnThWhszkC1mZhGJnUzh6v08GsqNiPLzwLuzzbX1uu7NnO2ui34nSORVQijRkNDaYP05Qnvp8lrCJcN2utxRxUWO3zOpq2jPHpLNaLhnR/bLrh9xQdVNgWZH/9SD530="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "gauravkgs1620"
    token:
      secure: "V47Y1pJQbe5JArtdgmqxycW9ZgiVI76EjkpoFDZg08/4EckmUGi8/M4xECUzmcsZVWrJLITi7ui7p3dVfI4wKjK29/NME+GwKWlrRCYFuNSoCNsorFGHBwEwCS6lqc0IFDGRHj6ndWxnoQku76LI4rDBlj/J8OnYyv9U6P8fSgP0A/6uQYMXjqULPPZ6mp0aKzZJqdapGuZeFMBqCJScPFGPg/VTyyDDD/tieUNRVgDEmz8gKElq62NbBtsRTejXWl1K+7yhGRdNzjgObrAsH4YL3cPLFay7nCFTOwwdXn9+D+QzwuXu9wWOga4m2300yVDNJri7rd7uTruBdny8bX1NZaNrnsV7kwI2BsC5Ldr8q9ClrweH8r0wivKEBsq6XxFp0ciZAQdhkYo91KS86G4SM5uMc0clI6OZbGZlW6Di1uf5rJajTLOsrblnKgLMDaS1tQ9Im6s+njhCZa2j9w8xWrPIxN/XqpcL5Rwf6FQr6xZeLSIjHmQHI2b6L6gNe6tsVel02w/KDgCBcLfAhvptNKvCea1ZEB7+9VA2l5pxq18blYEPfDX7ZHzfEWuKzOiL6aFczcZfCbuUeJ+pDzh4XQC6xLF2pqZI3aHntphQ9eV0yHX21rj8RMb+75P1R2b/5CBFgln2lH7jjRxUWHwVI8GHIet+TEvx2XuZanM="

jdk:
  - openjdk11
  
services:
  - docker

script: 
  - cd a4mee-api
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gauravkgs1620_a4mee
  
after_success:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=gauravkgs1620/a4mee
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
