sudo: required

language: java

env:
  global:
  - secure: k1sZPo9Ade67ypo473Z4lIupbHJRphc46XD/d3cbnB6NTNXuAx4NLBEPzGkLuoh+tz9X/BCrWpmkn7EJMCpHK46AWP5MmXUE6A/ORjLe1JfCsShy/uww1vN5aitzebzF/ONx8FEjut4XsocUP6UacUfaeO/SoWx3Uj4TOcA97glfFMsWU/GusS4wF7mLR1STOsBLhx9FbmpOfVOX3uBQgZoc12VByK304dZlUWpcX4nxpx7lK+iOjwKj9vaN6xNTie+U+q3iB4Up4KW6fPH50Rp5DbQaFIHuh9HhAESaTCu6GYOqnSN5D1ID4ZFfHDIF27qWGNc23z1nsS/bSC3CkE2s39rqeZ/2eYzWmHu6p7Gh6wkTiyBmtyCSSF5Wl7lr/ZP3pmo6FYMX3Gz4bsEGwgyJFbwOa4bnKJ1fe/X9AdM+f8KVSVHWeVz8nLyeDoFFO7kzkUS/w7cQpaurfNdoXQPzyR/J3XFxqOk4wf6fYosYs61aPheM4xdamWZE4vc50aU5LTw8OWZyGiSmTGqwuJzuSy/WhXqcsKlE7Pqwa7AUJgoJqUZoKBN1ZsCQOMLCKEnp82MrBRFbIARvHPQjSpL1D+utesLL8Hi1Pd8tSNzpP5UNw81Gtbw2QG5Vpgi6js+ylgEqDKRQLFCvUxs0LSl9uygd6/FaDDYNWxIVtsU=

addons:
  sonarcloud:
    organization: "gauravkgs1620-org"
    token:
      secure: $SONAR_TOKEN

jdk:
  - openjdk11
  
services:
  - docker

script: 
  - cd a4mee-api 
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
