sudo: required

language: java

env:
  global:
  - secure: mf3lM/d4DcVPiYTFQNTtiwuWzjGC0PduvFQoNB8Es72GXcS9lpQa0KnZxv148aFGlI9RqO/s1MN8Nuz1+BlzIVA5KtAKGXqnzei9coGYm2cZRDgbfn2On+31k8zCs+yhd9RtxQQQLyK5BEiBXDoc+JQlBtzZaOu6MkA5NH1wO923y9v+RaQAGV+uC/wJRknJK789G4L+U4S7pOacG8Hm5m99nH1x3+2caIIyX/CXYxM4qBjQYICK2EGLLgHKjACDKBmrV4nfdZ0+ChAIh5ccDAOrVZMD90Tp4awNX/eL58UTFJX0fM8QkNKI3uX05Va7t2QI8d5glRu5hjMk8KJu5sw4QGal2vpmeYYt49sXkjWbPxLlNReMkwQZpCWjcy/ZAFe4+CnCN+Ip/wpRBvjszq2zEOlqEW4UMREcmutULljDF/ROnWwn96Na4Re/wR2RU3XPbfnBgDREjcUj60kgKjY7yq6Z9zKdD6yK4ohv2StDA5eap1zjEE7ZRXiIEzlWig70BC+itBErQTzni0jhpYXLta8c3KKhovO87liLdguKn3dpMnqTLixj8gCJKKXIvYPkhtssEe9cIdLG96isdhKer1n4iI0Bc6u9z9KSBlvNuJO38VXcjtZRX6natWAXOjh3CI0DUfljllXW3up0IKN0ZTTwzTXTczKEO3x2o2w=

addons:
  sonarcloud:
    organization: "gauravkgs1620-org"
    token:
      secure: $SONAR_TOKEN

jdk:
  - openjdk11
  
services:
  - docker

script: 
  - cd a4mee-api 
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
